name: Synchronize to forked repo
on:
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORKED_REPO_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked_repo https://GangHyeokLee:${{secrets.FORKED_REPO_TOKEN}}@github.com/GangHyeokLee/BukguSwimming.git
          git config user.name "GangHyeokLee"
          git config user.email "rkdgur5381@gmail.com"

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main

      - name: Clean up
        run: |
          git remote remove forked-repo
